In [2]:
from bs4 import BeautifulSoup
import requests as r
import pandas as pd

# Using BeautifulSoup to extract table to DataFrame

In [91]:
url = "http://www.espn.com/nba/salaries"
data = r.get(url).text
soup = BeautifulSoup(data, 'html.parser')

In [92]:
table = soup.find_all('table')
len(table)

1

In [93]:
table = table[0]
heads = table.find_all('td')[:4]
columns = [head.text.strip() for head in heads]
nba_df = pd.DataFrame(columns =columns)
for index, row in enumerate(table):
    cols = row.find_all('td')
    add = []
    if 'RK' not in cols:
        rk = cols[0].text
        name = cols[1].text.strip()
        team = cols[2].text.strip()
        salary = cols[3].text
        add = [rk,name,team,salary]
        for i, val in zip(columns, add):
            nba_df.loc[index, i] = val
row_del = nba_df[nba_df.RK == 'RK']
nba_df = nba_df.drop(index=row_del.index)
nba_df.index =  [i for i in range(len(nba_df))]
nba_df

    RK                         NAME                    TEAM       SALARY
0    1            Stephen Curry, PG   Golden State Warriors  $48,070,014
1    2        Russell Westbrook, PG      Los Angeles Lakers  $47,063,478
2    3             LeBron James, SF      Los Angeles Lakers  $44,474,988
3    4             Kevin Durant, PF           Brooklyn Nets  $44,119,845
4    5             Bradley Beal, SG      Washington Wizards  $43,279,250
5    6           Damian Lillard, PG  Portland Trail Blazers  $42,492,492
6    7    Giannis Antetokounmpo, PF         Milwaukee Bucks  $42,492,492
7    8            Kawhi Leonard, SF             LA Clippers  $42,492,492
8    9              Paul George, SG             LA Clippers  $42,492,492
9   10            Klay Thompson, SG   Golden State Warriors  $40,600,080
10  11               Rudy Gobert, C  Minnesota Timberwolves  $38,172,414
11  12            Anthony Davis, PF      Los Angeles Lakers  $37,980,720
12  13          Khris Middleton, SF         Milwaukee Bucks  $37,948,276
13  14             Jimmy Butler, SF              Miami Heat  $37,653,300
14  15            Tobias Harris, PF      Philadelphia 76ers  $37,633,050
15  16              Zach LaVine, SG           Chicago Bulls  $37,096,500
16  17              Luka Doncic, PG        Dallas Mavericks  $37,095,000
17  18               Trae Young, PG           Atlanta Hawks  $37,095,000
18  19             Kyrie Irving, PG           Brooklyn Nets  $36,934,550
19  20            Pascal Siakam, PF         Toronto Raptors  $35,448,672
20  21              Ben Simmons, PG           Brooklyn Nets  $35,448,672
21  22        Kristaps Porzingis, C      Washington Wizards  $33,833,400
22  23             Devin Booker, SG            Phoenix Suns  $33,833,400
23  24        Karl-Anthony Towns, C  Minnesota Timberwolves  $33,833,400
24  25             Jrue Holiday, PG         Milwaukee Bucks  $33,665,040
25  26               Joel Embiid, C      Philadelphia 76ers  $33,616,770
26  27           Andrew Wiggins, SF   Golden State Warriors  $33,616,770
27  28              CJ McCollum, SG    New Orleans Pelicans  $33,333,333
28  29              Nikola Jokic, C          Denver Nuggets  $33,047,804
29  30             James Harden, SG      Philadelphia 76ers  $33,000,000
30  31           Brandon Ingram, SF    New Orleans Pelicans  $31,650,600
31  32             Jamal Murray, PG          Denver Nuggets  $31,650,000
32  33         D'Angelo Russell, PG  Minnesota Timberwolves  $31,377,750
33  34  Shai Gilgeous-Alexander, PG   Oklahoma City Thunder  $30,913,750
34  35             Deandre Ayton, C            Phoenix Suns  $30,913,750
35  36       Michael Porter Jr., SF          Denver Nuggets  $30,913,750
36  37         Donovan Mitchell, SG     Cleveland Cavaliers  $30,913,750
37  38               Bam Adebayo, C              Miami Heat  $30,351,780
38  39           Gordon Hayward, SF       Charlotte Hornets  $30,075,000
39  40        Jaren Jackson Jr., PF       Memphis Grizzlies  $28,946,605

# Using pd.read_html()

In [107]:
df_list = pd.read_html(url)
df_list = df_list[0]

In [109]:
head = df_list.iloc[0,:]
df_list.columns = head
row_del = df_list[df_list.RK == 'RK']
df_list = df_list.drop(index=row_del.index)
df_list.index =  [i for i in range(len(df_list))]
df_list

0   RK                         NAME                    TEAM       SALARY
0    1            Stephen Curry, PG   Golden State Warriors  $48,070,014
1    2        Russell Westbrook, PG      Los Angeles Lakers  $47,063,478
2    3             LeBron James, SF      Los Angeles Lakers  $44,474,988
3    4             Kevin Durant, PF           Brooklyn Nets  $44,119,845
4    5             Bradley Beal, SG      Washington Wizards  $43,279,250
5    6           Damian Lillard, PG  Portland Trail Blazers  $42,492,492
6    7    Giannis Antetokounmpo, PF         Milwaukee Bucks  $42,492,492
7    8            Kawhi Leonard, SF             LA Clippers  $42,492,492
8    9              Paul George, SG             LA Clippers  $42,492,492
9   10            Klay Thompson, SG   Golden State Warriors  $40,600,080
10  11               Rudy Gobert, C  Minnesota Timberwolves  $38,172,414
11  12            Anthony Davis, PF      Los Angeles Lakers  $37,980,720
12  13          Khris Middleton, SF         Milwaukee Bucks  $37,948,276
13  14             Jimmy Butler, SF              Miami Heat  $37,653,300
14  15            Tobias Harris, PF      Philadelphia 76ers  $37,633,050
15  16              Zach LaVine, SG           Chicago Bulls  $37,096,500
16  17              Luka Doncic, PG        Dallas Mavericks  $37,095,000
17  18               Trae Young, PG           Atlanta Hawks  $37,095,000
18  19             Kyrie Irving, PG           Brooklyn Nets  $36,934,550
19  20            Pascal Siakam, PF         Toronto Raptors  $35,448,672
20  21              Ben Simmons, PG           Brooklyn Nets  $35,448,672
21  22        Kristaps Porzingis, C      Washington Wizards  $33,833,400
22  23             Devin Booker, SG            Phoenix Suns  $33,833,400
23  24        Karl-Anthony Towns, C  Minnesota Timberwolves  $33,833,400
24  25             Jrue Holiday, PG         Milwaukee Bucks  $33,665,040
25  26               Joel Embiid, C      Philadelphia 76ers  $33,616,770
26  27           Andrew Wiggins, SF   Golden State Warriors  $33,616,770
27  28              CJ McCollum, SG    New Orleans Pelicans  $33,333,333
28  29              Nikola Jokic, C          Denver Nuggets  $33,047,804
29  30             James Harden, SG      Philadelphia 76ers  $33,000,000
30  31           Brandon Ingram, SF    New Orleans Pelicans  $31,650,600
31  32             Jamal Murray, PG          Denver Nuggets  $31,650,000
32  33         D'Angelo Russell, PG  Minnesota Timberwolves  $31,377,750
33  34  Shai Gilgeous-Alexander, PG   Oklahoma City Thunder  $30,913,750
34  35             Deandre Ayton, C            Phoenix Suns  $30,913,750
35  36       Michael Porter Jr., SF          Denver Nuggets  $30,913,750
36  37         Donovan Mitchell, SG     Cleveland Cavaliers  $30,913,750
37  38               Bam Adebayo, C              Miami Heat  $30,351,780
38  39           Gordon Hayward, SF       Charlotte Hornets  $30,075,000
39  40        Jaren Jackson Jr., PF       Memphis Grizzlies  $28,946,605